-- Belize Connect Jobs (M24) — enum ADD VALUEs on existing enums, isolated in their
-- own migration (Postgres: a new enum value can't be used in the same tx it's added).

ALTER TYPE "AuditAction" ADD VALUE 'EMPLOYER_PROFILE_UPSERTED';
ALTER TYPE "AuditAction" ADD VALUE 'JOB_SEEKER_PROFILE_UPSERTED';
ALTER TYPE "AuditAction" ADD VALUE 'JOB_CATEGORY_MANAGED';
ALTER TYPE "AuditAction" ADD VALUE 'JOB_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'JOB_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'JOB_SUBMITTED';
ALTER TYPE "AuditAction" ADD VALUE 'JOB_MODERATED';
ALTER TYPE "AuditAction" ADD VALUE 'JOB_PUBLISHED';
ALTER TYPE "AuditAction" ADD VALUE 'JOB_CLOSED';
ALTER TYPE "AuditAction" ADD VALUE 'JOB_ARCHIVED';
ALTER TYPE "AuditAction" ADD VALUE 'JOB_APPLICATION_SUBMITTED';
ALTER TYPE "AuditAction" ADD VALUE 'JOB_APPLICATION_STATUS_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE 'JOB_APPLICATION_WITHDRAWN';
ALTER TYPE "AuditAction" ADD VALUE 'JOB_INTERVIEW_SCHEDULED';
ALTER TYPE "AuditAction" ADD VALUE 'JOB_INTERVIEW_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'JOB_REPORTED';
ALTER TYPE "AuditAction" ADD VALUE 'JOB_REPORT_RESOLVED';
ALTER TYPE "NotificationCategory" ADD VALUE 'JOB';
ALTER TYPE "ConversationContext" ADD VALUE 'JOB_APPLICATION';
