-- AlterEnum: add Marketing (M26) values to existing enums (isolated per Postgres enum rules).
ALTER TYPE "AuditAction" ADD VALUE 'PROMOTION_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'PROMOTION_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'PROMOTION_SUBMITTED';
ALTER TYPE "AuditAction" ADD VALUE 'PROMOTION_MODERATED';
ALTER TYPE "AuditAction" ADD VALUE 'PROMOTION_PUBLISHED';
ALTER TYPE "AuditAction" ADD VALUE 'PROMOTION_STATUS_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE 'PROMOTION_REPORTED';
ALTER TYPE "AuditAction" ADD VALUE 'PROMOTION_REPORT_RESOLVED';
ALTER TYPE "AuditAction" ADD VALUE 'CAMPAIGN_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'CAMPAIGN_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'CAMPAIGN_STATUS_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE 'COUPON_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'COUPON_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'COUPON_STATUS_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE 'COUPON_REDEEMED';

-- AlterEnum
ALTER TYPE "NotificationCategory" ADD VALUE 'PROMOTION';
