-- Reviews & Ratings (Phase 4 · M19) — AuditAction value additions (isolated per PG rule).
ALTER TYPE "AuditAction" ADD VALUE 'REVIEW_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'REVIEW_EDITED';
ALTER TYPE "AuditAction" ADD VALUE 'REVIEW_MODERATED';
ALTER TYPE "AuditAction" ADD VALUE 'REVIEW_RESPONSE_ADDED';
ALTER TYPE "AuditAction" ADD VALUE 'REVIEW_RESPONSE_EDITED';
ALTER TYPE "AuditAction" ADD VALUE 'REVIEW_REPORTED';
ALTER TYPE "AuditAction" ADD VALUE 'REVIEW_REPORT_RESOLVED';
