import { randomUUID } from 'node:crypto';
import {
  BadRequestException,
  Inject,
  Injectable,
  Logger,
  ServiceUnavailableException,
  type OnModuleInit,
} from '@nestjs/common';
import {
  CreateBucketCommand,
  DeleteObjectCommand,
  GetObjectCommand,
  HeadBucketCommand,
  HeadObjectCommand,
  PutObjectCommand,
  S3Client,
} from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { ENV } from '../config/config.module';
import { storageEnabled, type Env } from '../config/env';

export interface ObjectMetadata {
  contentType: string;
  sizeBytes: number;
}

export type StorageHealth = 'ok' | 'not_configured' | 'error';

type Visibility = 'private' | 'public';

/**
 * S3-compatible object storage. Works with **MinIO** (local dev) and
 * **Cloudflare R2** (cloud) selected via STORAGE_PROVIDER — the S3 API is the
 * same; only endpoint/region/credentials/bucket differ (all env-driven).
 *
 * Two buckets:
 *  - PRIVATE (verification documents, admin attachments): never public; access
 *    only through short-lived signed URLs generated by the API after
 *    authorization + ownership checks.
 *  - PUBLIC (future: vendor logos, public images): served via a CDN/custom-domain
 *    base URL when configured, else a signed URL. No public objects exist yet in
 *    Phase 1 — this is preparation only.
 */
@Injectable()
export class StorageService implements OnModuleInit {
  private readonly logger = new Logger(StorageService.name);
  private readonly enabled: boolean;
  private readonly client: S3Client | null;

  constructor(@Inject(ENV) private readonly env: Env) {
    this.enabled = storageEnabled(env);
    // Only construct an S3 client when storage is actually configured, so we
    // never hold localhost/minio placeholder endpoints in production.
    this.client = this.enabled
      ? new S3Client({
          region: env.STORAGE_REGION,
          endpoint: env.STORAGE_ENDPOINT,
          forcePathStyle: env.STORAGE_FORCE_PATH_STYLE,
          credentials: {
            accessKeyId: env.STORAGE_ACCESS_KEY_ID,
            secretAccessKey: env.STORAGE_SECRET_ACCESS_KEY,
          },
        })
      : null;
  }

  isEnabled(): boolean {
    return this.enabled;
  }

  private requireClient(): S3Client {
    if (!this.enabled || !this.client) {
      throw new ServiceUnavailableException(
        'Object storage is not configured. File uploads are unavailable until STORAGE_PROVIDER (e.g. r2) and its credentials are set.',
      );
    }
    return this.client;
  }

  private bucketFor(v: Visibility): string {
    return v === 'public' ? this.env.STORAGE_PUBLIC_BUCKET : this.env.STORAGE_BUCKET;
  }

  async onModuleInit(): Promise<void> {
    if (!this.enabled) {
      this.logger.warn(
        `Object storage is NOT configured (STORAGE_PROVIDER=${this.env.STORAGE_PROVIDER}, env=${this.env.NODE_ENV}). ` +
          'The API will run normally; file-upload/signed-URL endpoints return 503 until Cloudflare R2 is configured.',
      );
      return;
    }
    await this.ensureBucket('private');
    await this.ensureBucket('public');
  }

  /**
   * Report storage health for the readiness probe. Returns 'not_configured'
   * (a non-failing state) when storage is intentionally disabled.
   */
  async healthStatus(): Promise<StorageHealth> {
    if (!this.enabled || !this.client) return 'not_configured';
    try {
      await this.client.send(new HeadBucketCommand({ Bucket: this.bucketFor('private') }));
      return 'ok';
    } catch {
      return 'error';
    }
  }

  /**
   * Ensure a bucket exists. For local MinIO we create it if missing. For R2,
   * buckets are provisioned out-of-band (dashboard/API with elevated creds), so
   * we only verify reachability and warn — we never assume creation rights.
   * No-op when storage is disabled.
   */
  async ensureBucket(v: Visibility = 'private'): Promise<void> {
    if (!this.enabled || !this.client) return;
    const Bucket = this.bucketFor(v);
    try {
      await this.client.send(new HeadBucketCommand({ Bucket }));
      return;
    } catch {
      if (this.env.STORAGE_PROVIDER !== 'minio') {
        this.logger.warn(
          `Storage bucket "${Bucket}" not reachable (provider=${this.env.STORAGE_PROVIDER}); create it in the provider console.`,
        );
        return;
      }
      try {
        await this.client.send(new CreateBucketCommand({ Bucket }));
        this.logger.log(`Created ${v} storage bucket "${Bucket}".`);
      } catch (err) {
        this.logger.warn(`Bucket ensure for "${Bucket}" reported: ${String(err)}`);
      }
    }
  }

  /** Namespaced, unguessable storage key under the given owner-scoped prefix. */
  buildKey(prefix: string, fileName: string): string {
    const safe = fileName.replace(/[^\w.\-]+/g, '_').slice(-80);
    return `${prefix}/${randomUUID()}/${safe}`;
  }

  /**
   * Ownership guard: a stored key must live under the exact owner-scoped prefix
   * before we ever attach it to a record. Prevents a user from referencing
   * another user's object by guessing/replaying a key.
   */
  assertKeyInNamespace(key: string, expectedPrefix: string): void {
    if (!key.startsWith(`${expectedPrefix}/`)) {
      throw new BadRequestException('Storage key does not belong to you.');
    }
  }

  /** Presigned PUT URL for a PRIVATE object the client uploads directly to. */
  async presignUpload(
    key: string,
    contentType: string,
    visibility: Visibility = 'private',
  ): Promise<{ uploadUrl: string; key: string; expiresIn: number }> {
    const client = this.requireClient();
    const command = new PutObjectCommand({
      Bucket: this.bucketFor(visibility),
      Key: key,
      ContentType: contentType,
    });
    const uploadUrl = await getSignedUrl(client, command, {
      expiresIn: this.env.STORAGE_SIGNED_URL_TTL,
    });
    return { uploadUrl, key, expiresIn: this.env.STORAGE_SIGNED_URL_TTL };
  }

  /** Short-lived GET URL for viewing a PRIVATE object (admin document review). */
  async presignDownload(
    key: string,
    visibility: Visibility = 'private',
  ): Promise<{ url: string; expiresIn: number }> {
    const client = this.requireClient();
    const command = new GetObjectCommand({ Bucket: this.bucketFor(visibility), Key: key });
    const url = await getSignedUrl(client, command, {
      expiresIn: this.env.STORAGE_SIGNED_URL_TTL,
    });
    return { url, expiresIn: this.env.STORAGE_SIGNED_URL_TTL };
  }

  /**
   * URL for a PUBLIC object: a stable CDN/custom-domain URL when configured,
   * otherwise a signed URL (dev fallback). Never used for private documents.
   */
  async publicUrl(key: string): Promise<string> {
    if (this.env.STORAGE_PUBLIC_BASE_URL) {
      return `${this.env.STORAGE_PUBLIC_BASE_URL.replace(/\/$/, '')}/${key}`;
    }
    return (await this.presignDownload(key, 'public')).url;
  }

  /** Delete an object. Best-effort: never throws (callers delete DB rows regardless). */
  async deleteObject(key: string, visibility: Visibility = 'private'): Promise<void> {
    if (!this.enabled || !this.client) return;
    try {
      await this.client.send(
        new DeleteObjectCommand({ Bucket: this.bucketFor(visibility), Key: key }),
      );
    } catch (err) {
      this.logger.warn(`Failed to delete object "${key}": ${String(err)}`);
    }
  }

  /**
   * Inspect an uploaded object to read its REAL content type and size. Returns
   * null when the object does not exist. This is the source of truth for stored
   * metadata — not client-declared values.
   */
  async headObject(key: string, visibility: Visibility = 'private'): Promise<ObjectMetadata | null> {
    const client = this.requireClient();
    try {
      const res = await client.send(
        new HeadObjectCommand({ Bucket: this.bucketFor(visibility), Key: key }),
      );
      return {
        contentType: res.ContentType ?? 'application/octet-stream',
        sizeBytes: Number(res.ContentLength ?? 0),
      };
    } catch {
      return null;
    }
  }
}
