/** Canonical audit action codes. Mirrors Prisma `AuditAction` enum. */
export const AUDIT_ACTIONS = [
  'USER_REGISTERED',
  'USER_LOGGED_IN',
  'USER_SUSPENDED',
  'USER_RESTORED',
  'EMAIL_VERIFIED',
  'PASSWORD_RESET',
  'ROLE_APPLICATION_SUBMITTED',
  'ROLE_APPLICATION_MORE_INFO_REQUESTED',
  'ROLE_APPLICATION_INFO_PROVIDED',
  'ROLE_APPROVED',
  'ROLE_REJECTED',
  'ROLE_SUSPENDED',
  'ROLE_RESTORED',
  'ROLE_REVOKED',
  'ROLE_SWITCHED',
  'ADMIN_PERMISSION_GRANTED',
  'ADMIN_PERMISSION_REVOKED',
  'NOTIFICATION_BROADCAST',
  // ---- Marketplace: Categories (Phase 2 · M1) ----
  'CATEGORY_CREATED',
  'CATEGORY_UPDATED',
  'CATEGORY_DELETED',
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];
