-- Settlement & Earnings (Phase 3 · M18) — enum value additions (isolated per PG rule).
ALTER TYPE "PaymentStatus" ADD VALUE 'SETTLING';
ALTER TYPE "PaymentStatus" ADD VALUE 'SETTLED';
ALTER TYPE "AuditAction" ADD VALUE 'SETTLEMENT_CALCULATED';
ALTER TYPE "AuditAction" ADD VALUE 'SETTLEMENT_POSTED';
ALTER TYPE "AuditAction" ADD VALUE 'SETTLEMENT_FAILED';
ALTER TYPE "AuditAction" ADD VALUE 'ESCROW_RELEASED_SETTLEMENT';
ALTER TYPE "AuditAction" ADD VALUE 'DRIVER_EARNING_POSTED';
ALTER TYPE "AuditAction" ADD VALUE 'VENDOR_SETTLEMENT_POSTED';
ALTER TYPE "AuditAction" ADD VALUE 'PLATFORM_FEE_POSTED';
ALTER TYPE "AuditAction" ADD VALUE 'PAYMENT_SETTLING';
ALTER TYPE "AuditAction" ADD VALUE 'PAYMENT_SETTLED';
ALTER TYPE "AuditAction" ADD VALUE 'PLATFORM_FEE_CONFIG_UPDATED';
